name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          # This assumes a test file is available, e.g., tests/test_api.py
          python -m unittest discover tests

  cd:
    runs-on: ubuntu-latest
    needs: ci # Only run CD if CI passes
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DKER_USERNAME }}/mlops-iris-app:latest

      - name: Deploy to EC2 or Local Machine
        # This is a placeholder for a real deployment.
        # You might use SSH to connect to a server and run docker commands.
        run: |
          echo "Simulating deployment to a target machine..."
          echo "Run the image with: docker run -p 5000:5000 -d ${{ secrets.DOCKER_USERNAME }}/mlops-iris-app:latest"